### ISSUE TITLE
ExternalDependencyManager от сторонних SDK

### ISSUE THREAD

**Issue by Kuzma0pro0** [appmetrica/appmetrica-unity-plugin#5]
Сторонние SDK (Firebase, GPGS, Рекламные SDK) используют ExternalDependencyManager в корневой папке Assets и меняют ее по необходимости на более новую версию. Сейчас AppMetrica требует добавления ExternalDependencyManager в Packages, что вызовет конфликт с сторонними SDK. Стоит переработать этот момент.

**Comment by AlexanderMaximovich-azur** [comment]
Вы не обязаны класть ExternalDependencyManager в папку Assets. С появлением UPM это даже скорее вредно, зачем в репозитории хранить то что можно подтянуть пакетом?)
