### ISSUE TITLE
How to turn off Auto Collected Ad Revenue event from ironSource?

### ISSUE THREAD

**Issue by lan-indiez** [appmetrica/appmetrica-unity-plugin#6]
We're receiving 2 duplicate Ad Revenue event because of Auto Collected option is enabled, how can I turn it off?
`2024/05/22 18:10:53.570 18427 18671 Info AppMetrica [com.***] : [131e8ebd-xxxx-xxxx-xxxx-xxxxxxxx93b6] AdRevenue Received: AdRevenue{adRevenue=0.0000429999, currency='USD', adType=OTHER, adNetwork='facebook', adUnitId='<null>', adUnitName='<null>', adPlacementId='<null>', adPlacementName='DefaultBanner', precision='CPM', payload=null, autoCollected=true}
2024/05/22 18:10:53.607 18427 18671 Info AppMetrica [com.***] : [131e8ebd-xxxx-xxxx-xxxx-xxxxxxxx93b6] AdRevenue Received: AdRevenue{adRevenue=0.000042999900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, currency='USD', adType=BANNER, adNetwork='facebook', adUnitId='<null>', adUnitName='Bidding', adPlacementId='<null>', adPlacementName='banner', precision='<null>', payload={"ad_format":"banner","session_id":"1716376240381"}, autoCollected=false}`

**Comment by NesterovichAlexey** [comment]
Hi! 
Do you see duplicate only in logs or also in web interface?
Auto-collection can be turned off by adding to `launcherTemplate.gradle`:
```gradle
configurations.configureEach {
    exclude group: 'io.appmetrica.analytics', module: 'analytics-ad-revenue'
}
```

**Comment by lan-indiez** [comment]
> Hi! Do you see duplicate only in logs or also in web interface? Auto-collection can be turned off by adding to `launcherTemplate.gradle`:
> 
> ```groovy-gradle
> configurations.configureEach {
>     exclude group: 'io.appmetrica.analytics', module: 'analytics-ad-revenue'
> }
> ```

Hi @NesterovichAlexey I see duplicate in both side logs and web interface.

Let me try your suggestion

**Comment by lan-indiez** [comment]
> Hi! Do you see duplicate only in logs or also in web interface? Auto-collection can be turned off by adding to `launcherTemplate.gradle`:
> 
> ```groovy-gradle
> configurations.configureEach {
>     exclude group: 'io.appmetrica.analytics', module: 'analytics-ad-revenue'
> }
> ```

It worked, thank you so much :)

**Comment by lan-indiez** [comment]
Hi @NesterovichAlexey ,

I missed this option for iOS, can you give me the same solution for iOS apps?

**Comment by NesterovichAlexey** [comment]
> Hi @NesterovichAlexey ,
> 
> I missed this option for iOS, can you give me the same solution for iOS apps?

Hi @lan-indiez!

There is no automatic AdRevenue collection in iOS and you don’t need to turn anything off.
