### ISSUE TITLE
Yandex Ads error with Android SDK 7.0.0

### ISSUE THREAD

**Issue by lan-indiez** [appmetrica/appmetrica-unity-plugin#8]
I'm using Yandex Ads ver 7.4.0 and AppMetrica SDK version 7.0.0 and I found this error:
```
08-09 15:52:59.068	com.indiez.nonogram	16067	-	W	YandexAds	 [Integration] Incorrect AppMetrica Version. The minimum supported version of AppMetrica SDK is 6.0.0 (inclusive) and the maximum supported version is 7.0.0 (exclusive). And the current version of AppMetrica SDK is 7.0.0	
08-09 15:53:03.984	com.indiez.nonogram	16067	-	E	YandexAds	 [Integration] Found following errors for banner ad type: 	
08-09 15:53:03.984	com.indiez.nonogram	16067	-	E	YandexAds	  - Incorrect AppMetrica Version. The minimum supported version of AppMetrica SDK is 6.0.0 (inclusive) and the maximum supported version is 7.0.0 (exclusive). And the current version of AppMetrica SDK is 7.0.0
``` 

How can I fix this?

**Comment by NesterovichAlexey** [comment]
Hi! Please write to [Yandex Ads support](https://ads.yandex.com/helpcenter/en/support/contact). This is a problem on their side.

**Comment by lan-indiez** [comment]
Hi @NesterovichAlexey 
I have asked Yandex Ads team and they said I need to talk with your team :(

So what can I do for now?

**Comment by NesterovichAlexey** [comment]
@lan-indiez, I'm sorry it happened this way. I can offer the following options.

You can force use `com.yandex.android:mobileads:7.5.0` in gradle file. This version supports AppMetrica SDK Android 7.0.0 and higher. But I can't guarantee that Yandex Mobile Ads Unity Plugin 7.4.0 will work with it normally.

You can also use AppMetrica Unity Plugin 6.1.0, which uses AppMetrica SDK Android 6.5.0. And this error will disappear. And wait until Yandex Mobile Ads Unity Plugin supports Yandex Mobile Ads SDK Android 7.5.0.
